name: prana_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7
  url_launcher: ^6.3.0
  agora_rtc_engine: ^6.3.0
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.8

  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  provider: ^6.1.5+1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome_boy.png
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/ambulance.jpg
    - assets/images/child.jpg
    - assets/images/fire.jpg
    - assets/images/mental.jpg
    - assets/images/poison.jpg
    - assets/images/women.jpeg
    - assets/images/emer.jpg
    - assets/images/logo.jpeg
    - assets/images/profile1.jpg