name: prana_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.10.4
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  provider: ^6.1.5+1
  firebase_core: ^4.7.0
  image: ^4.1.3
  url_launcher: ^6.3.0   # ✅ ADDED — was missing, caused all import errors

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/welcome_boy.png
   - assets/images/google.png
   - assets/images/facebook.png
   - assets/images/instagram.png
   - assets/images/ambulance.jpg
   - assets/images/child.jpg
   - assets/images/fire.jpg
   - assets/images/mental.jpg
   - assets/images/poison.jpg
   - assets/images/women.jpeg
   - assets/images/emer.jpg
   - assets/images/logo.jpeg
   - assets/model/model_unquant.tflite
   - assets/model/labels.txt